export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAILURE = "USER_LOGOUT_FAILURE";

export const AGENT_ALL_RESERVATIONS_SUCCESS = "AGENT_ALL_RESERVATIONS_SUCCESS";
export const AGENT_APPROVE_RESERVATION_SUCCESS =
  "AGENT_APPROVE_RESERVATION_SUCCESS";
export const AGENT_GET_ALL_CITIES_SUCCESS = "AGENT_GET_ALL_CITIES_SUCCESS";

export const CUSTOMER_ALL_RESERVATIONS_SUCCESS =
  "CUSTOMER_ALL_RESERVATIONS_SUCCESS";

export const CUSTOMER_RESERVATION_APPROVED_SUCCESS =
  "USER_RESERVATION_APPROVED_SUCCESS";
export const CUSTOMER_ALL_FLIGHTS_SUCCESS = "CUSTOMER_ALL_FLIGHTS_SUCCESS"
export const CUSTOMER_NEW_RESERVATION_SUCCESS = "CUSTOMER_NEW_RESERVATION_SUCCESS"