export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAILURE = "USER_LOGOUT_FAILURE";

export const AGENT_ALL_RESERVATIONS_SUCCESS = "AGENT_ALL_RESERVATIONS_SUCCESS";
export const AGENT_APPROVE_RESERVATION_SUCCESS =
  "AGENT_APPROVE_RESERVATION_SUCCESS";
export const AGENT_GET_ALL_CITIES_SUCCESS = "AGENT_GET_ALL_CITIES_SUCCESS";
export const AGENT_NEW_RESERVATION_FROM_CUSTOMER =
  "AGENT_NEW_RESERVATION_FROM_CUSTOMER";
export const AGENT_CANCEL_FLIGHT_FROM_ADMINISTRATOR_SUCCESS =
  "AGENT_CANCEL_FLIGHT_FROM_ADMINISTRATOR_SUCCESS";

export const CUSTOMER_ALL_RESERVATIONS_SUCCESS =
  "CUSTOMER_ALL_RESERVATIONS_SUCCESS";
export const CUSTOMER_RESERVATION_APPROVED_SUCCESS =
  "USER_RESERVATION_APPROVED_SUCCESS";
export const CUSTOMER_ALL_FLIGHTS_SUCCESS = "CUSTOMER_ALL_FLIGHTS_SUCCESS";
export const CUSTOMER_NEW_FLIGHT_FROM_AGENT = "CUSTOMER_NEW_FLIGHT_FROM_AGENT";
export const CUSTOMER_CANCEL_FLIGHT_FROM_ADMINISTRATOR_SUCCESS =
  "CUSTOMER_CANCEL_FLIGHT_FROM_ADMINISTRATOR_SUCCESS";

export const ADMINISTRATOR_ALL_FLIGHTS_SUCCESS =
  "ADMINISTRATOR_ALL_FLIGHTS_SUCCESS";
export const ADMINISTRATOR_NEW_USER_CREATE_SUCCESS =
  "ADMINISTRATOR_NEW_USER_CREATE_SUCCESS";
export const ADMINISTRATOR_CANCEL_FLIGHT_SUCCESS =
  "ADMINISTRATOR_CANCEL_FLIGHT_SUCCESS";
